/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IACL,
  IACLInterface,
} from "../../../contracts/FHELegacyVault.sol/IACL";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "delegator",
        type: "address",
      },
      {
        internalType: "address",
        name: "delegate",
        type: "address",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "getUserDecryptionDelegationExpirationDate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IACL__factory {
  static readonly abi = _abi;
  static createInterface(): IACLInterface {
    return new Interface(_abi) as IACLInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IACL {
    return new Contract(address, _abi, runner) as unknown as IACL;
  }
}
