/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHELegacyVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedHeirs"
      | "confidentialProtocolId"
      | "createVault"
      | "extendReleaseTime"
      | "getEncryptedKey"
      | "getEncryptedKeyAsOwner"
      | "getHeirVaults"
      | "getUserVaults"
      | "getVaultMetadata"
      | "grantAccess"
      | "grantAccessToMultiple"
      | "isAuthorized"
      | "revokeAccess"
      | "vaultExists"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "ReleaseTimeExtended"
      | "VaultCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedHeirs",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [string, string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extendReleaseTime",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedKeyAsOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHeirVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultMetadata",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccessToMultiple",
    values: [string, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vaultExists", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "authorizedHeirs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendReleaseTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedKeyAsOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHeirVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccessToMultiple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultExists",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [vaultId: string, heir: AddressLike];
  export type OutputTuple = [vaultId: string, heir: string];
  export interface OutputObject {
    vaultId: string;
    heir: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [vaultId: string, heir: AddressLike];
  export type OutputTuple = [vaultId: string, heir: string];
  export interface OutputObject {
    vaultId: string;
    heir: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseTimeExtendedEvent {
  export type InputTuple = [vaultId: string, newTimestamp: BigNumberish];
  export type OutputTuple = [vaultId: string, newTimestamp: bigint];
  export interface OutputObject {
    vaultId: string;
    newTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vaultId: string,
    owner: AddressLike,
    cid: string,
    releaseTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    owner: string,
    cid: string,
    releaseTimestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    owner: string;
    cid: string;
    releaseTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHELegacyVault extends BaseContract {
  connect(runner?: ContractRunner | null): FHELegacyVault;
  waitForDeployment(): Promise<this>;

  interface: FHELegacyVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedHeirs: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createVault: TypedContractMethod<
    [
      _vaultId: string,
      _cid: string,
      _encryptedKey: BytesLike,
      _inputProof: BytesLike,
      _releaseTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  extendReleaseTime: TypedContractMethod<
    [_vaultId: string, _newTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedKey: TypedContractMethod<[_vaultId: string], [string], "view">;

  getEncryptedKeyAsOwner: TypedContractMethod<
    [_vaultId: string],
    [string],
    "view"
  >;

  getHeirVaults: TypedContractMethod<[_heir: AddressLike], [string[]], "view">;

  getUserVaults: TypedContractMethod<[_user: AddressLike], [string[]], "view">;

  getVaultMetadata: TypedContractMethod<
    [_vaultId: string],
    [
      [string, string, bigint, bigint] & {
        owner: string;
        cid: string;
        releaseTimestamp: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [_vaultId: string, _heir: AddressLike],
    [void],
    "nonpayable"
  >;

  grantAccessToMultiple: TypedContractMethod<
    [_vaultId: string, _heirs: AddressLike[]],
    [void],
    "nonpayable"
  >;

  isAuthorized: TypedContractMethod<
    [_vaultId: string, _address: AddressLike],
    [boolean],
    "view"
  >;

  revokeAccess: TypedContractMethod<
    [_vaultId: string, _heir: AddressLike],
    [void],
    "nonpayable"
  >;

  vaultExists: TypedContractMethod<[_vaultId: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedHeirs"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      _vaultId: string,
      _cid: string,
      _encryptedKey: BytesLike,
      _inputProof: BytesLike,
      _releaseTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "extendReleaseTime"
  ): TypedContractMethod<
    [_vaultId: string, _newTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedKey"
  ): TypedContractMethod<[_vaultId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedKeyAsOwner"
  ): TypedContractMethod<[_vaultId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getHeirVaults"
  ): TypedContractMethod<[_heir: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserVaults"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaultMetadata"
  ): TypedContractMethod<
    [_vaultId: string],
    [
      [string, string, bigint, bigint] & {
        owner: string;
        cid: string;
        releaseTimestamp: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [_vaultId: string, _heir: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantAccessToMultiple"
  ): TypedContractMethod<
    [_vaultId: string, _heirs: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [_vaultId: string, _address: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [_vaultId: string, _heir: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultExists"
  ): TypedContractMethod<[_vaultId: string], [boolean], "view">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseTimeExtended"
  ): TypedContractEvent<
    ReleaseTimeExtendedEvent.InputTuple,
    ReleaseTimeExtendedEvent.OutputTuple,
    ReleaseTimeExtendedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(string,address)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(string,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "ReleaseTimeExtended(string,uint256)": TypedContractEvent<
      ReleaseTimeExtendedEvent.InputTuple,
      ReleaseTimeExtendedEvent.OutputTuple,
      ReleaseTimeExtendedEvent.OutputObject
    >;
    ReleaseTimeExtended: TypedContractEvent<
      ReleaseTimeExtendedEvent.InputTuple,
      ReleaseTimeExtendedEvent.OutputTuple,
      ReleaseTimeExtendedEvent.OutputObject
    >;

    "VaultCreated(string,address,string,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
